- resources/views/pages/SuperAdminLayanan.blade.php
refactor: adjust margin left and margin top in Layanan page
> refactor: adjust margin left and margin top in Layanan page

- resources/views/pages/SuperAdminDashboard.blade.php
refactor: change font in Dashboard Page
> refactor: change font in Dashboard Page

- resources/views/components/sidebar.blade.php
- resources/views/pages/SuperAdminCabang.blade.php
- resources/views/pages/SuperAdminDashboard.blade.php
- resources/views/pages/SuperAdminDetailCabang.blade.php
- resources/views/pages/SuperAdminDetailPenangguhan.blade.php
- resources/views/pages/SuperAdminEditCabang.blade.php
- resources/views/pages/SuperAdminFAQ.blade.php
- resources/views/pages/SuperAdminLayanan.blade.php
- resources/views/pages/SuperAdminPenangguhan.blade.php
- resources/views/pages/SuperAdminTambahCabang.blade.php
- routes/web.php
also add effect interactive on suspenssion page, and adjust several element on FAQ page
> refactor: adjust margin and size font page tittle on every pages

- resources/views/pages/SuperAdminLayanan.blade.php
- resources/views/pages/SuperAdminTambahTerapis.blade.php
- resources/views/pages/SuperAdminTerapis.blade.php
refactor: change background color in layanan page and terapis page
> refactor: change background color in layanan page and terapis page

- resources/views/pages/SuperAdminAduanPelanggan.blade.php
- resources/views/pages/SuperAdminCabang.blade.php
- resources/views/pages/SuperAdminDashboard.blade.php
- resources/views/pages/SuperAdminDetailAduan.blade.php
- resources/views/pages/SuperAdminDetailPenangguhan.blade.php
- resources/views/pages/SuperAdminDetailTerapis.blade.php
- resources/views/pages/SuperAdminFAQ.blade.php
- resources/views/pages/SuperAdminKaryawan.blade.php
- resources/views/pages/SuperAdminKaryawanBuatAkun.blade.php
- resources/views/pages/SuperAdminKaryawanDetailAkun.blade.php
- resources/views/pages/SuperAdminKaryawanDetailAkunFinance.blade.php
- resources/views/pages/SuperAdminLayanan.blade.php
- resources/views/pages/SuperAdminPelanggan.blade.php
- resources/views/pages/SuperAdminPelangganDetailAkun.blade.php
- resources/views/pages/SuperAdminPenangguhan.blade.php
- resources/views/pages/SuperAdminTambahTerapis.blade.php
- resources/views/pages/SuperAdminTerapis.blade.php
refactor: delete extends in all page that not have any function
> refactor: delete extends in all page that not have any function

- resources/views/pages/SuperAdminDetailPesanan.blade.php
- resources/views/pages/SuperAdminPesanan.blade.php
feat: add layout in Pesanan Page
> feat: add layout in Pesanan Page

- app/Http/Controllers/LayananController.php
- app/Http/Controllers/LoginController.php
- app/Models/LayananTambahan.php
- app/Models/LayananUtama.php
- resources/views/pages/SuperAdminLandingPage.blade.php
- resources/views/pages/SuperAdminLayanan.blade.php
- routes/web.php
feat(layanan): add CRUD to table layanan utama and layanan tambahan
> feat(layanan): add CRUD to table layanan utama and layanan tambahan

- resources/views/pages/SuperAdminLayanan.blade.php
refactor(layanan): add padding and margin in column status table layanan utama
> refactor(layanan): add padding and margin in column status table layanan utama

- app/Http/Controllers/AduanController.php
- resources/views/pages/SuperAdminAduanPelanggan.blade.php
- resources/views/pages/SuperAdminDetailAkunReportTerapis.blade.php
- resources/views/pages/SuperAdminDetailPenangguhan.blade.php
in every actions in penangguhan and detailakunreportterapis
> refactor: add spinner and success

- app/Http/Controllers/TerapisController.php
- app/Models/Terapis.php
refactor(Terapis): clean code in controller and model
> refactor(Terapis): clean code in controller and model

- app/Http/Controllers/TerapisController.php
- resources/views/pages/SuperAdminTerapis.blade.php
- routes/web.php
feat(Terapis): add function Get,Delete,Search, and Pagination
> feat(Terapis): add function Get,Delete,Search, and Pagination

- resources/views/pages/SuperAdminTambahCabang.blade.php
fix(Tambah Terapis): improve page layout for consistency
> fix(Tambah Terapis): improve page layout for consistency

- app/Http/Controllers/TerapisController.php
- app/Models/Terapis.php
- resources/views/pages/SuperAdminDetailTerapis.blade.php
- resources/views/pages/SuperAdminTerapis.blade.php
- routes/web.php
feat(Detail Terapis); add GET function to all data except Transaksi Terakhir section from database
> feat(Detail Terapis); add GET function to all data except Transaksi Terakhir section from database

- resources/views/pages/SuperAdminLayanan.blade.php
feat(Layanan): add sorting function in layanan tambahan table and clean code
> feat(Layanan): add sorting function in layanan tambahan table and clean code

- resources/views/pages/SuperAdminTerapis.blade.php
refactor(Terapis): improve page layout for better UI consistency
> refactor(Terapis): improve page layout for better UI consistency

- resources/views/pages/SuperAdminTerapis.blade.php
feat(Terapis): fix pagination function
> feat(Terapis): fix pagination function

- app/Http/Controllers/KaryawanController.php
- app/Models/Karyawan.php
- app/Models/SuperAdmin.php
- database/migrations/2025_08_08_174248_create_karyawans_table.php
- resources/views/pages/SuperAdminKaryawan.blade.php
- resources/views/pages/SuperAdminKaryawanBuatAkun.blade.php
- resources/views/pages/SuperAdminKaryawanDetailAkun.blade.php
- resources/views/pages/SuperAdminKaryawanDetailAkunFinance.blade.php
- routes/web.php
update Backend :
-  create karyawan ke data akun admin
- Create Karyawan ke Data Akun Finance
- Detail Akun Karywan Admin
- Deatil Akun Karyawan Finance
> Update-Ziza 4.0

- resources/views/components/navbar.blade.php
- resources/views/layouts/notifikasi.blade.php
- resources/views/pages/SuperAdminNotifikasi.blade.php
- routes/web.php
feat(notifikasi): add notifications page with routing
> feat(notifikasi): add notifications page with routing

- resources/views/pages/SuperAdminTerapis.blade.php
> feat: add sorting function

- resources/views/components/sidebar.blade.php
refactor: adjust spacing and margin between item
> refactor: adjust spacing and margin between item

- app/Http/Controllers/TerapisController.php
- app/Models/Terapis.php
- database/migrations/2025_08_14_115625_add_birth_place_to_therapists_table.php
fix: bug in TherapistsController
> fix: bug in TherapistsController

- app/Http/Controllers/DashboardController.php
- resources/views/pages/SuperAdminDashboard.blade.php
feat(Dashboard): connect Recent Orders table to backend
> feat(Dashboard): connect Recent Orders table to backend

- app/Http/Controllers/DashboardController.php
- resources/views/pages/SuperAdminDashboard.blade.php
- routes/web.php
feat(dashboard): connect recent orders table details to backend
> feat(dashboard): connect recent orders table details to backend
